[build]
  base = ""
  command = "npm install && cd frontend && npm install && npm run build"
  publish = "frontend/build"

[functions]
  directory = "src/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
