[build]
  base = ""
  # More detailed build commands to ensure all dependencies are installed correctly
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"

# Environment variable configuration - add non-sensitive env vars here
[build.environment]
  NODE_ENV = "production"

# Redirects for the frontend-only version
# Note: We no longer need the API functions redirect

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
