services:
  - type: web
    name: linkedin-js-tips-poster
    env: node
    buildCommand: npm install && cd frontend && npm install && npm run build && cd ..
    startCommand: node src/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: LINKEDIN_API_KEY
        sync: false
      - key: LINKEDIN_API_SECRET
        sync: false
      - key: LINKEDIN_REDIRECT_URI
        sync: false
      - key: LINKEDIN_ACCESS_TOKEN
        sync: false
      - key: LINKEDIN_PERSON_ID
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    autoDeploy: true
